"""add analysis_synced_at staleness column

Revision ID: 586ee6e0113b
Revises: c533485a2e5d
Create Date: 2026-08-30 10:53:52.433041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586ee6e0113b'
down_revision: Union[str, Sequence[str], None] = 'c533485a2e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('analysis_synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'analysis_synced_at')
    # ### end Alembic commands ###
