"""create stories and story_sources tables

Revision ID: 7d4481dd7d11
Revises: 1ec1c376db7c
Create Date: 2026-08-30 09:41:57.006261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d4481dd7d11'
down_revision: Union[str, Sequence[str], None] = '1ec1c376db7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_topic'), 'stories', ['topic'], unique=False)
    op.create_table('story_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('story_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_sources_story_id'), 'story_sources', ['story_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_sources_story_id'), table_name='story_sources')
    op.drop_table('story_sources')
    op.drop_index(op.f('ix_stories_topic'), table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###
