"""add story synthesis fields (cause, timeline, analysis, what_if_seeds, source headline/summary)

Revision ID: c533485a2e5d
Revises: 7d4481dd7d11
Create Date: 2026-08-30 10:10:27.263759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c533485a2e5d'
down_revision: Union[str, Sequence[str], None] = '7d4481dd7d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills the 180+ existing rows created before this
    # migration; the ORM-side Python defaults only apply to new rows.
    op.add_column('stories', sa.Column('cause', sa.String(), nullable=False, server_default=''))
    op.add_column('stories', sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('stories', sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{}'))
    op.add_column('stories', sa.Column('what_if_seeds', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='[]'))
    op.add_column('story_sources', sa.Column('headline', sa.String(), nullable=False, server_default=''))
    op.add_column('story_sources', sa.Column('summary', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_sources', 'summary')
    op.drop_column('story_sources', 'headline')
    op.drop_column('stories', 'what_if_seeds')
    op.drop_column('stories', 'analysis')
    op.drop_column('stories', 'timeline')
    op.drop_column('stories', 'cause')
    # ### end Alembic commands ###
